daysUntilStale: 14
daysUntilClose: 14
exemptMilestones: true
staleLabel: waiting-reply

exemptLabels:
- thinking

markComment: >
  Hi there! This has been automatically marked as stale because it has not
  had activity in the past 14 days. It will be closed in 14 days if no
  further activity takes place.

closeComment: >
  Hi there! This has been closed due to lack of activity. Please comment
  if you would like it re-opened.
  
